
FROM node:22-alpine as builder
WORKDIR /app


COPY package.json package-lock.json .
# Copy the startup script into the image
RUN npm install --only=production --force --frozen-lockfile --verbose --no-audit --ignore-scripts
COPY . .
RUN npm run build --verbose

FROM node:22-alpine as runner
WORKDIR /app

COPY --from=builder /app/package.json .
COPY --from=builder /app/package-lock.json .
COPY --from=builder /app/next.config.mjs .
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# Set the script as the default command to run on container start
CMD ["node", "server.js"]

EXPOSE 3000
