import { EDraftStatus, EVersionStatus } from "./enums";
import { IUserInfo } from "./app.interface";

export interface IVersion {
  createDate: number;
  updateDate: number;
  id: number;
  chatThreadId?: number;
  versionNumber: string;
  status: EDraftStatus | EVersionStatus;
  state: "draft" | "version" | "public";
  content?: string;
  outline?: string;
  postId: number;
  repoId: number;
  categoryId: number;
  documentId: number;
  dislikeCount: number;
  likeCount: number;
  hash: string;
  shareCount: number;
  metadata: string;
  favoriteCount: number;
  commentCount: number;
  changeLog: string;
  draftId: number;
  message?: string;
  creator?: {
    name: string;
    userName: string;
    ssoId: number;
  };
  fileHash?: {
    fileExtension: string;
    fileName: string;
    hash: string;
  };
  contentType?: string;
  repoUserGroupHash?: string;
  categoryUserGroupHash?: string;
  documentTitle?: string;
  repoName?: string;
}

export interface IComment {
  id: number;
  text: string;
  timestamp: number;
  user: {
    id: number;
    name: string;
    ssoId: number;
    ssoIssuerCode: number;
    profileImage: string;
  };
  confirmed: boolean;
  numOfLikes: number;
  numOfComments: number;
  liked: boolean;
}

export declare interface IOutline extends ILevelObject {
  children: IOutline[];
}
export declare interface ILevelObject {
  id: string;
  tag: string;
  level: number;
  text?: string;
  userPostInfo?: IUserPostInfo;
}

export interface IUserPostInfo {
  postId: number;
  liked: boolean;
  disliked: boolean;
  favorite: boolean;
}

export interface IVersion_Blocking_Result {
  user: IUserInfo;
  blockTime: number;
  vId: number;
  onEnd: (result: boolean) => void;
}
export interface IShared_Version_Hash_Result {
  sharedHash: string;
}

export declare interface IFileDetail {
  file: File | null;
  isUploaded: boolean;
  fileHash?: string;
}

export declare interface ITinyLinkResult {
  urlOrContent: string;
  hash: string;
  visitCount: number;
  shortenObjectKind: string;
}

export declare interface IAddVersion {
  content: string;
  hash: string;
  id: number;
  outline: string;
  versionNumber: string;
}
export declare interface ITab {
  repoId: number;
  documentId: number;
  categoryId?: number;
  catGroupHash?: string;
  repoGroupHash?: string;
  type?: string;
  result: IVersion;
}
// Generated by https://quicktype.io

export interface IFileVersion {
  hash: string;
  fileName: string;
  fileExtension: string;
}
