export const config = {
  showOutline: false,
  padding: 0,
  includeItems: [
    "bold",
    "italic",
    "underline",
    "strikethrough",
    "fontSize",
    "alignment",
    "rtl",
    "ltr",
    "outdent",
    "indent",
    "highlight",
    "insertTable",
    "link",
    "clasorCode",
    "undo",
    "redo",
  ],
};
